stanze=[{"nome":"Entrata", "pos_in":["entrata"], "pos_fin":["entrata"], "peso":0, "porte":3, "colore":["blu"]},
    {"nome": "Anticamera", "pos_in":["uscita"], "pos_fin":["uscita"], "peso":0, "porte":4, "colore":["blu"]},
    {"nome":"Spare Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["blu"]},
    {"nome":"Parlor", "pos_in": ["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["blu"]},
    {"nome":"Billiard Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["blu"]},
    {"nome":"Closet", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":1, "colore":["blu"]},
    {"nome":"Storeroom", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":1, "colore":["blu"]},
    {"nome":"Nook", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["blu"]},
    {"nome":"Den", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":3, "colore":["blu"]},
    {"nome":"Pantry", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["blu"]},
    {"nome":"Drawing Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":3, "colore":["blu"]},
    {"nome":"Bedroom", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["rosa"]},
    {"nome":"Guest Bedroom", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":1, "colore":["rosa"]},
    {"nome":"Nursery", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":1, "colore":["rosa"]},
    {"nome":"Hallway", "pos_in":["ovunque"], "pos_fin":["interno"], "peso":2.94, "porte":3, "colore":["arancione"]},
    {"nome":"Corridor", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["arancione"]},
    {"nome":"Passageway", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":4, "colore":["arancione"]},
    {"nome":"Kitchen", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":2, "colore":["giallo"]},
    {"nome":"Chapel", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":2.94, "porte":3, "colore":["rosso"]},
    {"nome":"Walk-in Closet", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["blu"]},
    {"nome":"Rumpus Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["blu"]},
    {"nome":"Office", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["blu"]},
    {"nome":"The Pool", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["blu"]},
    {"nome":"Utility Closet", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["blu"]},
    {"nome":"Security", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["blu"]},
    {"nome":"Laboratory", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["blu"]},
    {"nome":"Coat Check", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["blu"]},
    {"nome":"Dining Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["blu"]},
    {"nome":"Observatory", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["blu"]},
    {"nome":"Boudoir", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["rosa"]},
    {"nome":"West Wing Hall", "pos_in":["ovunque"], "pos_fin":["lato sinistro"], "peso":1.15, "porte":3, "colore":["arancione"]},
    {"nome":"Terrace", "pos_in":["interno"], "pos_fin":["lato destro", "lato sinistro"], "peso":1.15, "porte":1, "colore":["verde"]},
    {"nome":"Patio", "pos_in":["ovunque"], "pos_fin":["lato destro", "lato sinistro"], "peso":1.15, "porte":2, "colore":["verde"]},
    {"nome":"Courtyard", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["verde"]},
    {"nome":"Greenhouse", "pos_in":["lato sinistro", "lato destro"], "pos_fin":["lato destro", "lato sinistro"], "peso":1.15, "porte":1, "colore":["verde"]},
    {"nome":"Commissary", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["giallo"]},
    {"nome":"The Armory", "pos_in":["Room 46"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["giallo", "nero"]},
    {"nome":"Lavatory", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["rosso"]},
    {"nome":"Gymnasium", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["rosso"]},
    {"nome":"Darkroom", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.15, "porte":3, "colore":["rosso"]},
    {"nome":"The Kennel", "pos_in":["STUDIO"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["blu"]},
    {"nome":"Solarium", "pos_in":["STUDIO"], "pos_fin":["interno"], "peso":1.15, "porte":1, "colore":["verde"]},
    {"nome":"Dormitory", "pos_in":["STUDIO"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["rosa"]},
    {"nome":"Planetarium", "pos_in":["OBS"], "pos_fin":["ovunque"], "peso":1.15, "porte":1, "colore":["blu"]},
    {"nome":"Tunnel", "pos_in":["BAS"], "pos_fin":["ovunque"], "peso":1.15, "porte":2, "colore":["arancione"]},
    {"nome":"Garage", "pos_in":["ovunque"], "pos_fin":["lato sinistro"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Music Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Wine Cellar", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Ballroom", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Study", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Library", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Boiler Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":3, "colore":["blu"]},
    {"nome":"Pump Room", "pos_in":["POOL"], "pos_fin":["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Workshop", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Sauna", "pos_in": ["POOL"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Mail Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Conference Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":3, "colore":["blu"]},
    {"nome":"Aquarium", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":3, "colore":["blu", "rosso", "verde", "giallo", "rosa", "arancione", "nero"]},
    {"nome":"Servant's Quarters", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["rosa"]},
    {"nome":"Bunk Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["rosa"]},
    {"nome":"East Wing Hall", "pos_in": ["ovunque"], "pos_fin": ["lato destro"], "peso":0.45, "porte":3, "colore":["arancione"]},
    {"nome":"Secret Passage", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["arancione"]},
    {"nome":"Foyer", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["arancione"]},
    {"nome":"Great Hall", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":4, "colore":["arancione"]},
    {"nome":"Cloister", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":0.45, "porte":4, "colore":["verde"]},
    {"nome":"Veranda", "pos_in": ["ovunque"], "pos_fin": ["lato destro", "lato sinistro"],"peso":0.45, "porte":2, "colore":["verde"]},
    {"nome":"Locksmith", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["giallo"]},
    {"nome":"Maid's Chamber", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["rosso", "rosa"]},
    {"nome":"Archives", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.45, "porte":4, "colore":["rosso"]},
    {"nome":"Dovecote", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Clock Tower", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":0.45, "porte":1, "colore":["blu"]},
    {"nome":"Classroom", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["blu"]},
    {"nome":"Vestibule", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":0.45, "porte":4, "colore":["arancione"]},
    {"nome":"Casino", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["giallo"]},
    {"nome":"Mechanarium", "pos_in": ["BAS"], "pos_fin": ["interno"], "peso":0.45, "porte":4, "colore":["blu"]},
    {"nome":"Treasure Trove", "pos_in": ["BAS"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["nero"]},
    {"nome":"Conservatory", "pos_in": ["TENDA"], "pos_fin": ["lato sinistro", "lato destro"], "peso":0.45, "porte":2, "colore":["verde"]},
    {"nome":"Lost & Found", "pos_in": ["BAS"], "pos_fin": ["ovunque"], "peso":0.45, "porte":2, "colore":["rosso"]},
    {"nome":"The Foundation", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":0.23, "porte":3, "colore":["blu"]},
    {"nome":"Rotunda", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":0.23, "porte":2, "colore":["blu"]},
    {"nome":"Gallery", "pos_in": ["Room 46"], "pos_fin": ["ovunque"], "peso":0.23, "porte":2, "colore":["blu"]},
    {"nome":"Room 8", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":2, "colore":["blu"]},
    {"nome":"Attic", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":1, "colore":["blu"]},
    {"nome":"Locker Room", "pos_in": ["POOL"], "pos_fin": ["ovunque"], "peso":0.23, "porte":3, "colore":["blu"]},
    {"nome":"Trophy Room", "pos_in": ["Room 46"], "pos_fin": ["ovunque"], "peso":0.23, "porte":2, "colore":["blu"]},
    {"nome":"Vault", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":1, "colore":["blu"]},
    {"nome":"Chamber of Mirrors", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":0.23, "porte":4, "colore":["blu"]},
    {"nome":"Drafting Studio", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":2, "colore":["blu"]},
    {"nome":"Freezer", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":1, "colore":["blu"]},
    {"nome":"Her Ladyship's Chamber", "pos_in": ["lato sinistro"], "pos_fin": ["lato sinistro"], "peso":0.23, "porte":1, "colore":["rosa"]},
    {"nome":"Master Bedroom", "pos_in": ["ovunque"], "pos_fin": ["lato destro"], "peso":1, "porte":0.23, "colore":["rosa"]},
    {"nome":"Morning Room","pos_in":["B&U"],"pos_fin":["lato destro","lato sinistro"],"peso":0.23,"porte":2,"colore":["verde"]},
    {"nome":"Secret Garden", "pos_in": ["ovunque"], "pos_fin": ["lato destro", "lato sinistro"], "peso":0.23, "porte":3, "colore":["verde"]},
    {"nome":"Showroom", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":2, "colore":["giallo"]},
    {"nome":"Laundry Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":1, "colore":["giallo"]},
    {"nome":"Gift Shop", "pos_in": ["Room 46"], "pos_fin": ["ovunque"], "peso":0.23, "porte":3, "colore":["giallo"]},
    {"nome":"Weight Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":4, "colore":["rosso"]},    
    {"nome":"Furnace", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":0.23, "porte":1, "colore":["rosso"]},
    {"nome":"Throne Room", "pos_in": ["BAS"], "pos_fin": ["ovunque"], "peso":0.23, "porte":3, "colore":["nero"]},
    {"nome":"Closed Exhibit","pos_in":["STU"],"pos_fin":["ovunque"],"peso":0.23,"porte":3,"colore":["rosso"]}]

stanze_l=[
    {"nome":"Walk-in Closet", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":1, "colore":["blu"]},
    {"nome":"Rumpus Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["blu"]},
    {"nome":"Office", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["blu"]},
    {"nome":"The Pool", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":3, "colore":["blu"]},
    {"nome":"Utility Closet", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":1, "colore":["blu"]},
    {"nome":"Security", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":3, "colore":["blu"]},
    {"nome":"Laboratory", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["blu"]},
    {"nome":"Coat Check", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":1, "colore":["blu"]},
    {"nome":"Dining Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":3, "colore":["blu"]},
    {"nome":"Observatory", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["blu"]},
    {"nome":"West Wing Hall", "pos_in":["ovunque"], "pos_fin":["lato sinistro"], "peso":0.05, "porte":3, "colore":["arancione"]},
    {"nome":"Terrace", "pos_in":["ovunque"], "pos_fin":["lato destro", "lato sinistro"], "peso":0.05, "porte":1, "colore":["verde"]},
    {"nome":"Patio", "pos_in":["ovunque"], "pos_fin":["lato destro", "lato sinistro"], "peso":0.05, "porte":2, "colore":["verde"]},
    {"nome":"Greenhouse", "pos_in":["lato sinistro", "lato destro"], "pos_fin":["lato destro", "lato sinistro"], "peso":0.05, "porte":1, "colore":["verde"]},
    {"nome":"Commissary", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["giallo"]},
    {"nome":"The Armory", "pos_in":["Room 46"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["giallo", "nero"]},
    {"nome":"The Kennel", "pos_in":["STUDIO"], "pos_fin":["ovunque"], "peso":0.05, "porte":2, "colore":["blu"]},
    {"nome":"Solarium", "pos_in":["STUDIO"], "pos_fin":["interno"], "peso":0.05, "porte":1, "colore":["verde"]},
    {"nome":"Dormitory", "pos_in":["STUDIO"], "pos_fin":["ovunque"], "peso":0.05, "porte":1, "colore":["rosa"]},
    {"nome":"Planetarium", "pos_in":["OBS"], "pos_fin":["ovunque"], "peso":0.05, "porte":1, "colore":["blu"]},
    {"nome":"Garage", "pos_in":["ovunque"], "pos_fin":["lato sinistro"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Wine Cellar", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Study", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Boiler Room", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.92, "porte":3, "colore":["blu"]},
    {"nome":"Pump Room", "pos_in":["POOL"], "pos_fin":["ovunque"], "peso":1.92, "porte":2, "colore":["blu"]},
    {"nome":"Workshop", "pos_in":["ovunque"], "pos_fin":["ovunque"], "peso":1.92, "porte":2, "colore":["blu"]},
    {"nome":"Sauna", "pos_in": ["POOL"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Mail Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Conference Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":3, "colore":["blu"]},
    {"nome":"Aquarium", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":3, "colore":["blu", "rosso", "verde", "giallo", "rosa", "arancione", "nero"]},
    {"nome":"Servant's Quarters", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["rosa"]},
    {"nome":"Bunk Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["rosa"]},
    {"nome":"East Wing Hall", "pos_in": ["ovunque"], "pos_fin": ["lato destro"], "peso":1.92, "porte":3, "colore":["arancione"]},
    {"nome":"Secret Passage", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["arancione"]},
    {"nome":"Great Hall", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":4, "colore":["arancione"]},
    {"nome":"Veranda", "pos_in": ["ovunque"], "pos_fin": ["lato destro", "lato sinistro"],"peso":1.92, "porte":2, "colore":["verde"]},
    {"nome":"Locksmith", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["giallo"]},
    {"nome":"Archives", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":1.92, "porte":4, "colore":["rosso"]},
    {"nome":"Dovecote", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":1.92, "porte":2, "colore":["blu"]},
    {"nome":"Clock Tower", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":1.92, "porte":1, "colore":["blu"]},
    {"nome":"Classroom", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":1.92, "porte":2, "colore":["blu"]},
    {"nome":"Vestibule", "pos_in": ["STUDIO"], "pos_fin": ["ovunque"], "peso":1.92, "porte":4, "colore":["arancione"]},
    {"nome":"Mechanarium", "pos_in": ["BAS"], "pos_fin": ["interno"], "peso":1.92, "porte":4, "colore":["blu"]},
    {"nome":"Treasure Trove", "pos_in": ["BAS"], "pos_fin": ["ovunque"], "peso":1.92, "porte":2, "colore":["nero"]},
    {"nome":"Conservatory", "pos_in": ["TENDA"], "pos_fin": ["lato sinistro", "lato destro"], "peso":1.92, "porte":2, "colore":["verde"]},
    {"nome":"Lost & Found", "pos_in": ["BAS"], "pos_fin": ["ovunque"], "peso":1.92, "porte":2, "colore":["rosso"]},
    {"nome":"The Foundation", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":3.85, "porte":3, "colore":["blu"]},
    {"nome":"Rotunda", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":3.85, "porte":2, "colore":["blu"]},
    {"nome":"Gallery", "pos_in": ["Room 46"], "pos_fin": ["ovunque"], "peso":3.85, "porte":2, "colore":["blu"]},
    {"nome":"Locker Room", "pos_in": ["POOL"], "pos_fin": ["ovunque"], "peso":3.85, "porte":3, "colore":["blu"]},
    {"nome":"Chamber of Mirrors", "pos_in": ["ovunque"], "pos_fin": ["interno"], "peso":3.85, "porte":4, "colore":["blu"]},
    {"nome":"Freezer", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":3.85, "porte":1, "colore":["blu"]},
    {"nome":"Her Ladyship's Chamber", "pos_in": ["lato sinistro"], "pos_fin": ["lato sinistro"], "peso":3.85, "porte":1, "colore":["rosa"]},
    {"nome":"Morning Room", "pos_in": ["B&U"], "pos_fin": ["lato destro", "lato sinistro"], "peso":3.85, "porte":2, "colore":["verde"]},
    {"nome":"Laundry Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":3.85, "porte":1, "colore":["giallo"]},
    {"nome":"Bookshop", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":3.85, "porte":2, "colore":["giallo"]},
    {"nome":"Gift Shop", "pos_in": ["Room 46"], "pos_fin": ["ovunque"], "peso":3.85, "porte":3, "colore":["giallo"]},
    {"nome":"Weight Room", "pos_in": ["ovunque"], "pos_fin": ["ovunque"], "peso":3.85, "porte":4, "colore":["rosso"]},    
    {"nome":"Closed Exhibit", "pos_in": ["STU"], "pos_fin": ["ovunque"], "peso":3.85, "porte":3, "colore":["rosso"]}]

stanze_esterne=[{"nome":"Toolshed", "peso":1, "colore":["blu"]}, {"nome":"Shelter", "peso":1, "colore":["blu"]},
    {"nome":"Schoolhouse", "peso":1, "colore":["blu"]}, {"nome":"Shrine", "peso":1, "colore":["blu"]},
    {"nome":"Root Cellar", "peso":1, "colore":["verde"]}, {"nome":"Hovel", "peso":1, "colore":["rosa"]},
    {"nome":"Trading Post", "peso":1, "colore":["giallo"]}, {"nome":"Tomb", "peso":1, "colore":["nero"]}]

stanze_specchi_sinistro=["Spare Room", "Den", "Pantry", "Workshop", "Boudoir", "West Wing Hall", "East Wing Hall", "Gymnasium"]

stanze_specchi_destro=["Parlor", "Billiard Room", "Closet", "Storeroom", "Wine Cellar", "Observatory", "Aquarium", "Passageway"]

aggiunte_specchi=["Spare Room", "Parlor", "Billiard Room", "Closet", "Storeroom", "Nook", "Den", "Pantry", "Bedroom", "Guest Bedroom", "Patio"
    "Nursery", "Hallway", "Corridor", "Passageway", "Walk-in Closet", "Rumpus Room", "Observatory", "West Wing Hall", "Terrace", "Vault"
    "Courtyard", "Lavatory", "Solarium", "Music Room", "Ballroom", "Bunk Room", "East Wing Hall", "Foyer", "Cloister", "Veranda", "Attic"
    "Maid's Chamber", "Archives", "Rotunda" , "Trophy Room" , "Her Ladyship's Chamber", "Master Bedroom", "Morning Room", "Weight Room"]

modifiche_cons= ["The Foundation", "Gallery", "Room 8", "Garage", "Locker Room", "Sauna", "Veranda", "Morning Room", "Secret Garden",
                 "Bookshop", "The Armory", "Classroom", "Conservatory", "Pump Room", "Dovecote", "Freezer", "Stanze esterne"]